const $=id=>document.getElementById(id), $$=q=>Array.from(document.querySelectorAll(q));
const api=async(path,opts={})=>{const r=await fetch(path,{cache:"no-store",...opts});const j=await r.json().catch(()=>({error:"Invalid server response"}));if(!r.ok)throw Error(j.error||("HTTP "+r.status));return j};
const post=(path,obj={})=>api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)});
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const tone=v=>{v=String(v||"").toUpperCase();if(["READY","PASS","VALID","SIGNED","ONLINE","CLEAN","ALLOW","YES","ACTIVE"].includes(v))return"pass";if(["FAIL","INVALID","ERROR","DENY"].includes(v))return"fail";if(["BLOCKED","DEV","PARTIAL","UNAVAILABLE","NOT_INSTALLED","SIGNATURES_MISSING","SANDBOX"].includes(v))return"warn";return"info"};
const titles={overview:"Protection Overview",activity:"Agent & Intake Activity",policy:"Policy",workspace:"Files & Scans",runtime:"Runtime",audit:"Audit",controls:"Controls",system:"System"};
let currentPath=".", selectedJob=null, systemCache=null;
function toast(msg,type=""){const n=$("toast");n.textContent=msg;n.className="toast show "+type;clearTimeout(toast.t);toast.t=setTimeout(()=>n.className="toast",3200)}
function statusPill(status){return '<span class="status-pill '+tone(status)+'">'+esc(status)+'</span>'}
function decisionChip(v){v=String(v||"EVENT").toUpperCase();return '<span class="decision-chip '+v.toLowerCase()+'">'+esc(v)+'</span>'}
function openView(name){$$(".view").forEach(n=>n.classList.toggle("active",n.id==="view-"+name));$$("#nav button").forEach(n=>n.classList.toggle("active",n.dataset.view===name));$("page-title").textContent=titles[name]||name;window.scrollTo(0,0);({overview:loadOverview,activity:loadActivity,policy:loadPolicy,workspace:loadWorkspace,runtime:loadRuntime,audit:loadAudit,controls:loadControls,system:loadSystem}[name]||(()=>{}))()}
$$("[data-view]").forEach(b=>b.onclick=()=>openView(b.dataset.view));$$("[data-open]").forEach(b=>b.onclick=()=>openView(b.dataset.open));
setInterval(()=>{$("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})},1000);
const search=$("global-search");search.addEventListener("input",()=>{const q=search.value.trim().toLowerCase(),v=document.querySelector(".view.active");v.querySelectorAll("article,.control-row-card,.dependency-row,.read-row,tr").forEach(n=>n.classList.toggle("search-hidden",!!q&&!n.textContent.toLowerCase().includes(q)))});document.addEventListener("keydown",e=>{if(e.key==="/"&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||"")){e.preventDefault();search.focus()}});

function layer(name,status,detail){return '<article class="layer-card"><div class="layer-top"><strong>'+esc(name)+'</strong>'+statusPill(status)+'</div><p>'+esc(detail)+'</p></article>'}
function simpleRow(k,v){return '<div class="simple-row"><span>'+esc(k)+'</span><strong>'+esc(v??"—")+'</strong></div>'}
function readRow(k,v){return '<div class="read-row"><small>'+esc(k)+'</small><span>'+esc(v??"Not available")+'</span></div>'}
function attention(title,detail,good=false){return '<div class="attention-item '+(good?"pass":"")+'"><i>'+(good?"✓":"!")+'</i><div><strong>'+esc(title)+'</strong><p>'+esc(detail)+'</p></div></div>'}

function getControl(s,id){return (s.assurance?.controls||[]).find(c=>c.id===id)||{}}
function controlUsable(s,id){return getControl(s,id).status==="PASS"}
function kvmReason(vm){return vm?.kvm?.reason||vm?.kvm?.error||"This host does not expose usable /dev/kvm hardware virtualization."}

async function loadOverview(){
  try{
    const [s,events,adv]=await Promise.all([api("/api/system"),api("/api/audit/events?limit=120"),api("/api/adversary")]);systemCache=s;
    const env=s.environment?.codespaces?"CODESPACES":"LOCAL HOST";$("env-badge").textContent=env;$("sidebar-host").textContent=env+" · "+(s.repo?.branch||"repo");
    const counts={ALLOW:0,SANDBOX:0,ESCALATE:0,DENY:0};events.forEach(e=>{const d=String(e.decision||"").toUpperCase();if(d in counts)counts[d]++});const total=Object.values(counts).reduce((a,b)=>a+b,0);
    $("metric-records").textContent=(s.audit?.records||0).toLocaleString();$("metric-denied").textContent=counts.DENY.toLocaleString();$("metric-review").textContent=counts.ESCALATE.toLocaleString();$("metric-agents").textContent=(adv.summary?.total_attackers||0).toLocaleString();

    const malwareStatus=s.malware?.ready?"READY":(s.malware?.status||"UNAVAILABLE");
    const auditStatus=s.audit?.configured?(s.audit.valid?"VALID":"INVALID"):"UNSET";
    const policyStatus=s.runtime?.policy_bundle?"SIGNED":"DEV";
    const sandboxStatus=(controlUsable(s,"SANDBOX.SECCOMP_STRICT")&&controlUsable(s,"SANDBOX.LANDLOCK"))?"READY":"PARTIAL";
    const vmStatus=s.vm?.kvm?.status==="PASS"?"READY":"BLOCKED";
    const sentinelStatus=String(s.sentinel?.verdict||"UNKNOWN").toUpperCase();
    const layers=[
      ["Policy",policyStatus,policyStatus==="SIGNED"?"Signed capability ceiling is loaded.":"Using development policy; production policy is not loaded."],
      ["Malware admission",malwareStatus,s.malware?.ready?"ClamAV and signed malware signatures are ready.":(s.malware?.error||"Scanner is not ready.")],
      ["Sandbox",sandboxStatus,sandboxStatus==="READY"?"Live sandbox controls have passed.":"Some deployment isolation controls are not live-proven in this session."],
      ["MicroVM",vmStatus,vmStatus==="READY"?"Hardware KVM is available on this host.":"The hardened KVM layer cannot launch on this host."],
      ["Audit",auditStatus,auditStatus==="VALID"?"The audit hash chain verifies.":(s.audit?.error||"Audit ledger needs attention.")],
      ["Agent Sentinel",sentinelStatus,"Current host heuristic verdict: "+sentinelStatus+"."]
    ];
    const ready=layers.filter(x=>tone(x[1])==="pass").length;$("layer-score").textContent=ready+"/"+layers.length;$("layer-grid").innerHTML=layers.map(x=>layer(...x)).join("");
    const prod=s.assurance?.deployment_complete===true;$("overall-state").textContent=prod?"Production controls pass":"BULL is running with partial deployment protections";$("overall-detail").textContent=prod?"All required deployment controls in the current assurance profile pass.":"Core BULL services are available, but one or more production-only controls are not active on this host.";$("top-protection").textContent=prod?"PROTECTED":"PARTIAL";$("top-protection").className=prod?"pass":"warn";$("sidebar-state").textContent=prod?"PROTECTED":"PARTIAL";$("sidebar-dot").className=prod?"pass":"";

    const issues=[];
    if(!s.runtime?.policy_bundle)issues.push(attention("Development policy mode","A signed production capability policy is not loaded. Policy evaluation still works, but this is not the production boundary."));
    if(!s.malware?.ready)issues.push(attention("Malware scanner needs setup",s.malware?.error||"ClamAV is not ready."));
    if(s.vm?.kvm?.status!=="PASS")issues.push(attention("Hardware MicroVM unavailable here",kvmReason(s.vm)+" The rest of BULL can still operate; use a KVM-capable Linux host for the MicroVM layer."));
    if(!s.vm?.assets_verified)issues.push(attention("Guest assets not cached","Verified BULL guest assets are not present yet. Download them from the Runtime page if you plan to run KVM."));
    if(s.audit?.valid===true)issues.push(attention("Audit ledger verified","The local tamper-evident audit chain is valid.",true));
    $("action-required").innerHTML=issues.join("");

    const colors={ALLOW:"#4db97a",SANDBOX:"#e5aa3a",ESCALATE:"#a46de2",DENY:"#e05b5f"};let start=0,parts=[];for(const k of ["ALLOW","SANDBOX","ESCALATE","DENY"]){const pct=total?counts[k]/total*100:25;parts.push(colors[k]+" "+start+"% "+(start+pct)+"%");start+=pct}$("decision-donut").style.background=total?"conic-gradient("+parts.join(",")+")":"#2a2d31";$("decision-total").textContent=total;$("decision-legend").innerHTML=["ALLOW","SANDBOX","ESCALATE","DENY"].map(k=>'<div class="legend-row"><i style="background:'+colors[k]+'"></i><span>'+k+'</span><b>'+counts[k]+'</b></div>').join("");
    $("overview-events").innerHTML=events.length?events.slice(-12).reverse().map(e=>'<tr><td>'+esc(e.timestamp?new Date(e.timestamp).toLocaleTimeString():"—")+'</td><td>'+decisionChip(e.decision||e.record_type)+'</td><td>'+esc(e.actor||"runtime")+'</td><td>'+esc(e.operation||"—")+'</td><td>'+esc(e.resource||"—")+'</td></tr>').join(""):'<tr><td colspan="5">No audit decisions recorded yet.</td></tr>';
    $("overview-repo").innerHTML=simpleRow("Branch",s.repo?.branch)+simpleRow("Commit",s.repo?.commit)+simpleRow("Working tree",s.repo?.dirty?"Changed":"Clean")+simpleRow("Remote",s.repo?.remote);
  }catch(e){toast(e.message,"error")}
}
$("overview-refresh").onclick=loadOverview;

function renderReadable(obj){if(!obj||typeof obj!=="object")return readRow("Value",obj);return Object.entries(obj).map(([k,v])=>{if(Array.isArray(v))v=v.join(", ");else if(v&&typeof v==="object")v=Object.entries(v).map(([a,b])=>a+": "+b).join(" · ");return readRow(k.replace(/_/g," "),v)}).join("")}

async function loadActivity(){try{const [s,a]=await Promise.all([api("/api/sentinel"),api("/api/adversary")]);$("sentinel-score").textContent=Number(s.score||0).toFixed(3);$("sentinel-verdict").textContent=String(s.verdict||"UNKNOWN").toUpperCase();$("sentinel-signals").innerHTML=renderReadable(s.signals||{});renderRegistry(a)}catch(e){toast(e.message,"error")}}
$("activity-refresh").onclick=loadActivity;
function renderRegistry(a){const rows=a.records||[];$("registry-rows").innerHTML=rows.length?rows.map(r=>'<tr><td>'+esc(r.attacker_id)+'</td><td>'+esc(r.label)+'</td><td>'+esc(r.swarm_id||"—")+'</td><td>'+esc(r.model_family||"—")+'</td><td>'+(r.quarantined?statusPill("QUARANTINED"):'<button class="link-button" data-q="'+esc(r.attacker_id)+'">Classify quarantine</button>')+'</td></tr>').join(""):'<tr><td colspan="5">No observed records yet.</td></tr>';$$("[data-q]").forEach(b=>b.onclick=async()=>{try{await post("/api/adversary/quarantine",{attacker_id:b.dataset.q});toast("Record classified for quarantine","success");loadActivity()}catch(e){toast(e.message,"error")}})}
$("agent-scan").onclick=async()=>{try{const payload=$("agent-url").value.trim()?{url:$("agent-url").value.trim()}:{text:$("agent-text").value};const r=await post("/api/agent-scan",payload);const c=r.counts||{};$("agent-scan-summary").className="scan-summary";$("agent-scan-summary").innerHTML='<div class="signal-grid">'+["agent","swarm","botnet","endpoint"].map(k=>'<div><small>'+esc(k.toUpperCase())+'</small><b>'+Number(c[k]||0)+'</b></div>').join("")+'</div><div class="readable">'+readRow("Source",r.source)+readRow("Bytes inspected",r.bytes)+readRow("Meaning",r.note)+'</div>';renderRegistry({records:(r.registry?.records||[])});loadActivity()}catch(e){$("agent-scan-summary").className="scan-summary";$("agent-scan-summary").innerHTML='<div class="human-message">'+esc(e.message)+'</div>'}};

const actionMap={read:{operation:"read",cap:"fs.read.project"},write:{operation:"write",cap:"fs.write.project"},execute:{operation:"execute",cap:"process.exec"},fetch:{operation:"fetch",cap:"network.outbound"},post:{operation:"post",cap:"network.post"},"credential.read":{operation:"credential.read",cap:"credential.read"},spawn:{operation:"spawn",cap:"agent.spawn"},message:{operation:"message",cap:"agent.message"},security:{operation:"modify",cap:"security_control.write"}};
function policyExample(type,root){return({read:root+"/README.md",write:root+"/tmp-output.txt",execute:"/usr/bin/python3",fetch:"https://example.com/",post:"https://example.com/api", "credential.read":"credential://example/service",spawn:"agent://child",message:"agent://peer",security:"/etc/security-control"}[type]||root)}
async function loadPolicy(){try{const r=await api("/api/repo");if(!$("policy-resource").value)$("policy-resource").value=policyExample($("policy-action").value,r.root)}catch{}}
$("policy-action").onchange=async()=>{const r=await api("/api/repo");$("policy-resource").value=policyExample($("policy-action").value,r.root)};
$("policy-evaluate").onclick=async()=>{try{const m=actionMap[$("policy-action").value],granted=$("policy-authority").value==="granted"?[m.cap]:[];const payload={actor:$("policy-actor").value,task:"Command Center policy evaluation",operation:m.operation,resource:$("policy-resource").value,capability:m.cap,granted_capabilities:granted,provenance:[$("policy-provenance").value],external_side_effect:$("policy-side-effect").checked,irreversible:$("policy-irreversible").checked};const r=await post("/api/policy/evaluate",payload);$("policy-result").className="decision-result";$("policy-result").innerHTML='<div class="result-badge '+String(r.decision).toLowerCase()+'">'+esc(r.decision)+'</div><p>Risk score <b>'+Number(r.risk||0).toFixed(2)+'</b>'+(r.hard_block?' · hard block':'')+'</p><div class="risk-bar"><i style="width:'+Math.round(Number(r.risk||0)*100)+'%"></i></div><h3>Why</h3><div class="reason-list">'+(r.reasons||[]).map(x=>'<div>'+esc(x)+'</div>').join("")+'</div>'}catch(e){$("policy-result").className="decision-result";$("policy-result").textContent=e.message}};

async function browse(path="."){const x=await api("/api/files?path="+encodeURIComponent(path));currentPath=x.path;$("browser-path").textContent=x.path;const el=$("repo-browser");el.innerHTML="";if(x.path!=="."){const up=document.createElement("button");up.className="file-button dir";up.textContent="↰ ..";up.onclick=()=>browse(x.path.split("/").slice(0,-1).join("/")||".");el.appendChild(up)}x.items.forEach(it=>{const b=document.createElement("button");b.className="file-button "+(it.dir?"dir":"");b.textContent=(it.dir?"▣ ":"· ")+it.name;b.onclick=()=>{if(it.dir){$("scan-target").value=it.path;browse(it.path)}else{$("scan-target").value=it.path;previewFile(it.path)}};el.appendChild(b)})}
async function previewFile(path){try{const x=await api("/api/file?path="+encodeURIComponent(path));$("preview-title").textContent=x.path;$("file-preview").textContent=x.content}catch(e){$("file-preview").textContent=e.message}}
async function loadWorkspace(){try{const [m]=await Promise.all([api("/api/system"),browse(currentPath)]);const s=m.malware||{};$("scanner-state").textContent=s.ready?"READY":(s.status||"UNAVAILABLE");$("scanner-detail").textContent=s.ready?"ClamAV + signed signatures are ready":(s.error||"Scanner unavailable")}catch(e){toast(e.message,"error")}}
$("workspace-refresh").onclick=loadWorkspace;
async function runScan(target){try{$("scan-result").className="scan-result";$("scan-result").textContent="Scanning "+target+"…";const r=await post("/api/malware/scan",{path:target,timeout:180});if(r.clean){$("scan-result").innerHTML='<div class="scan-good"><b>✓ CLEAN</b><span>'+Number(r.files_scanned||0).toLocaleString()+' file(s) scanned with '+esc(r.engine||"ClamAV")+'.</span></div>'}else{$("scan-result").innerHTML='<b style="color:var(--red)">DETECTIONS FOUND</b>'+(r.detections||[]).map(d=>'<div class="scan-detection"><strong>'+esc(d.signature)+'</strong><br>'+esc(d.path)+'</div>').join("")}}catch(e){$("scan-result").className="scan-result";$("scan-result").innerHTML='<div class="scan-detection">'+esc(e.message)+'</div>'}}
$("scan-target-button").onclick=()=>runScan($("scan-target").value||".");$("scan-all-button").onclick=()=>{$("scan-target").value=".";runScan(".")};

function checklist(label,status,detail){return '<div class="check-row '+tone(status)+'"><i></i><div><b>'+esc(label)+'</b><small>'+esc(detail)+'</small></div><span>'+esc(status)+'</span></div>'}
async function loadRuntime(){try{const v=await api("/api/vm");const kpass=v.kvm?.status==="PASS",toolsMissing=Object.entries(v.tools||{}).filter(([,x])=>!x).map(([k])=>k);$("runtime-summary").className="runtime-summary "+(kpass?"pass":"warn");$("runtime-summary").innerHTML='<div class="runtime-icon">⬢</div><div><h2>'+(kpass?"MicroVM host is ready":"MicroVM cannot run on this host")+'</h2><p>'+(kpass?"KVM hardware access is available. Verified guest assets and configuration still determine whether a specific launch can proceed.":esc(kvmReason(v))+" BULL's policy, malware, audit, Sentinel and other host protections still operate without the MicroVM layer.")+'</p></div>';$("runtime-checklist").innerHTML=checklist("KVM hardware access",kpass?"READY":"BLOCKED",kpass?"/dev/kvm is usable":kvmReason(v))+checklist("QEMU",v.tools?.["qemu-system-x86_64"]?"READY":"MISSING",v.tools?.["qemu-system-x86_64"]||"qemu-system-x86_64 not installed")+checklist("Verified guest assets",v.assets_verified?"READY":"NOT READY",v.assets_verified?"Guest files verified":v.asset_error||"Guest assets have not been cached yet")+checklist("Launcher configuration",v.microvm_config?"READY":"OPTIONAL",v.microvm_config||"No private launcher config supplied");$("vm-run").disabled=!kpass||toolsMissing.length>0;$("runtime-advanced").innerHTML=renderReadable({mode:v.architecture?.mode,control_channel:v.architecture?.control_channel,audit_channel:v.architecture?.audit_channel,software_emulation_fallback:v.architecture?.software_emulation_fallback});await refreshJobs()}catch(e){toast(e.message,"error")}}
$("runtime-refresh").onclick=loadRuntime;
async function refreshJobs(){try{const jobs=await api("/api/jobs");$("job-list").innerHTML=jobs.length?jobs.map(j=>'<button class="job-item" data-job="'+esc(j.id)+'"><b class="'+String(j.status).toLowerCase()+'">'+esc(j.status)+'</b><span>'+esc(j.command_label)+'</span><small>'+esc(new Date((j.started||0)*1000).toLocaleString())+'</small></button>').join(""):'<div class="job-log empty">No runtime jobs launched in this session.</div>';$$("[data-job]").forEach(b=>b.onclick=()=>selectJob(b.dataset.job));if(selectedJob)await selectJob(selectedJob,false)}catch(e){toast(e.message,"error")}}
async function selectJob(id,remember=true){if(remember)selectedJob=id;try{const [j,l]=await Promise.all([api("/api/job?id="+encodeURIComponent(id)),api("/api/job/log?id="+encodeURIComponent(id))]);$("job-log").className="job-log";$("job-log").innerHTML=readRow("Status",j.status)+readRow("Operation",j.command_label)+readRow("Evidence directory",j.output_dir)+'<pre>'+esc(l.log||"No log output yet.")+'</pre>'}catch(e){$("job-log").textContent=e.message}}
$("jobs-refresh").onclick=refreshJobs;$("vm-install-assets").onclick=async()=>{try{const j=await post("/api/vm/install-assets");selectedJob=j.id;toast("Verified guest download started","success");refreshJobs()}catch(e){toast(e.message,"error")}};$("vm-plan").onclick=async()=>{try{const r=await api("/api/microvm/plan");$("job-log").className="job-log";$("job-log").innerHTML=readRow("Validated",r.validated?"YES":"NO")+'<pre>'+esc(r.output||"No output")+'</pre>'}catch(e){toast(e.message,"error")}};$("vm-run").onclick=async()=>{try{const j=await post("/api/vm/run",{case:$("vm-case").value});selectedJob=j.id;toast("MicroVM integration job started","success");refreshJobs()}catch(e){toast(e.message,"error")}};$("deployment-run").onclick=async()=>{try{const j=await post("/api/deployment/run");selectedJob=j.id;toast("Deployment check started","success");refreshJobs()}catch(e){toast(e.message,"error")}};

async function loadAudit(){try{const [a,e]=await Promise.all([api("/api/audit"),api("/api/audit/events?limit=200")]);$("audit-configured").textContent=a.configured?"YES":"NO";$("audit-valid").textContent=a.valid===true?"VALID":a.valid===false?"INVALID":"—";$("audit-records").textContent=Number(a.records||0).toLocaleString();$("audit-head").textContent=(a.head_hash||"—").slice(0,12);$("audit-rows").innerHTML=e.length?e.reverse().map(x=>'<tr><td>'+esc(x.timestamp?new Date(x.timestamp).toLocaleString():"—")+'</td><td>'+decisionChip(x.decision||x.record_type)+'</td><td>'+esc(x.actor||"runtime")+'</td><td>'+esc(x.operation||"—")+'</td><td>'+esc(x.capability||"—")+'</td><td>'+esc(x.resource||"—")+'</td><td>'+esc((x.reasons||[]).join("; ")||"—")+'</td></tr>').join(""):'<tr><td colspan="7">No audit events recorded.</td></tr>'}catch(e){toast(e.message,"error")}}
$("audit-refresh").onclick=loadAudit;

async function loadControls(){try{const a=await api("/api/assurance");const controls=a.controls||[],phases=["source","deployment","release","external"];$("control-summary").innerHTML=phases.map(p=>{const rows=controls.filter(c=>c.phase===p),pass=rows.filter(c=>["PASS","IMPLEMENTED"].includes(c.status)).length;return'<article><small>'+p.toUpperCase()+'</small><b>'+pass+'/'+rows.length+'</b></article>'}).join("");$("control-groups").innerHTML=phases.map(p=>{const rows=controls.filter(c=>c.phase===p);return'<section class="control-group"><header><h2>'+p[0].toUpperCase()+p.slice(1)+'</h2><span>'+rows.length+' controls</span></header>'+rows.map(c=>'<div class="control-row-card"><div>'+statusPill(c.status)+'</div><div><h3>'+esc(c.title||c.id)+'</h3><p>'+esc(c.detail||"No additional detail.")+'</p><code>'+esc(c.id)+'</code></div></div>').join("")+'</section>'}).join("")}catch(e){toast(e.message,"error")}}
$("controls-refresh").onclick=loadControls;

function renderDeps(d){$("dependency-grid").innerHTML=(d.items||[]).map(x=>'<div class="dependency-row '+(x.installed?"pass":"")+'"><i></i><div><b>'+esc(x.label)+'</b><small>'+esc(x.command)+(x.id==="clamav"?" · signatures "+(x.database_ready?"ready":"missing"):"")+'</small></div><span>'+(x.installed?"READY":"MISSING")+'</span></div>').join("")}
async function loadSystem(){try{const [s,d,b]=await Promise.all([api("/api/system"),api("/api/host/dependencies"),api("/api/brand")]);renderDeps(d);$("runtime-config").innerHTML=renderReadable(s.runtime||{});$("brand-revision").textContent=b.revision||"";$("brand-meta").innerHTML="Approved source: <b>"+esc(b.source?.file||"")+"</b> · "+esc(b.source?.note||"");$("brand-assets").innerHTML=Object.keys(b.files||{}).map(name=>'<div class="brand-asset '+(name.includes("primary.svg")?"light":"")+'"><img src="/brand/'+encodeURIComponent(name)+'" alt="'+esc(name)+'"><span>'+esc(name)+'</span></div>').join("")}catch(e){toast(e.message,"error")}}
$("system-install").onclick=async()=>{try{const j=await post("/api/host/install");selectedJob=j.id;toast("Host dependency repair started","success");openView("runtime");refreshJobs()}catch(e){toast(e.message,"error")}};

loadOverview();
setInterval(()=>{if($("view-overview").classList.contains("active"))loadOverview()},5000);
