const $=id=>document.getElementById(id);
const $$=q=>Array.from(document.querySelectorAll(q));
const api=async(path,opts={})=>{const r=await fetch(path,{cache:"no-store",...opts});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j};
const post=(path,obj={})=>api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(obj)});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const statusClass=s=>String(s||"").toLowerCase().replace(/[^a-z0-9_-]/g,"_");
const TITLES={main:"Overview",repo:"Repository",workspace:"Workspace",visualization:"Execution Path",runtime:"Runtime / VM",controls:"Controls",logs:"Audit",agents:"Agents",settings:"System"};
let lastSystem=null,currentRepoPath=".",selectedJob=null,lastScan={agent:0,swarm:0,botnet:0,endpoint:0};

function toast(message,tone=""){const n=$("toast");n.textContent=message;n.className="toast show "+tone;clearTimeout(toast.t);toast.t=setTimeout(()=>n.className="toast",3400)}
function tone(status){const v=String(status||"").toUpperCase();if(["PASS","READY","VALID","ONLINE","SIGNED","CLEAN","ALLOW","TRUE"].includes(v))return"pass";if(["FAIL","ERROR","INVALID","DENY"].includes(v))return"fail";if(["BLOCKED","PARTIAL","DEV","NOT_INSTALLED","SIGNATURES_MISSING","UNAVAILABLE","FALSE"].includes(v))return"warn";return"info"}
function decisionBadge(v){v=String(v||"event").toUpperCase();return '<span class="decision '+statusClass(v)+'">'+esc(v)+'</span>'}
function setHealth(card,status,detail){const c=$(card),base=card.replace("card-","hc-");c.className="health-card "+tone(status);$(base+"-status").textContent=status;$(base+"-detail").textContent=detail}

const LABELS={root:"Repository root",branch:"Branch",commit:"Commit",remote:"Git remote",dirty:"Working tree changed",status:"Status",configured:"Configured",valid:"Integrity valid",records:"Records",head_hash:"Head checkpoint",policy_bundle:"Signed policy bundle",integrity_manifest:"Signed runtime manifest",microvm_configured:"MicroVM configuration",audit_ledger:"Audit ledger",remote_anchor:"Remote audit anchor",seccomp_profile:"Seccomp profile",cgroup_parent:"Delegated cgroup v2",snapshot_root:"Snapshot scratch",hardware_approval:"Hardware approval",assets_verified:"Guest assets verified",asset_manifest:"Guest asset manifest",asset_error:"Guest asset error",microvm_config:"MicroVM config",config_error:"Config error",software_emulation_fallback:"Software-emulation fallback",persistent_session:"Persistent VM session",guest_network_device:"Guest network device",control_channel:"Control channel",audit_channel:"Audit channel",returncode:"Return code",output_dir:"Evidence directory",command_label:"Operation",started:"Started",finished:"Finished",database_count:"Signature databases",binary:"Binary"};
function humanLabel(k){k=String(k||"");return LABELS[k]||k.replace(/[_-]+/g," ").replace(/\b\w/g,m=>m.toUpperCase())}
function humanScalar(key,v){if(v===null||v===undefined||v==="")return'<span class="human-muted">Not available</span>';if(typeof v==="boolean")return'<span class="human-badge '+(v?"yes":"no")+'">'+(v?"YES":"NO")+'</span>';if(typeof v==="number"){if((String(key).includes("started")||String(key).includes("finished"))&&v>1e9)return'<span>'+esc(new Date(v*1000).toLocaleString())+'</span>';return'<strong class="human-number">'+esc(v.toLocaleString())+'</strong>'}const s=String(v),u=s.toUpperCase();if(["PASS","FAIL","BLOCKED","RUNNING","READY","VALID","INVALID","ALLOW","SANDBOX","ESCALATE","DENY","IMPLEMENTED","EXTERNAL","CLEAN","NOT_INSTALLED","SIGNATURES_MISSING"].includes(u))return'<span class="human-badge '+statusClass(u)+'">'+esc(u)+'</span>';const codeLike=String(key).includes("path")||String(key).includes("hash")||String(key).includes("commit")||String(key).includes("url")||s.startsWith("/")||/^[a-f0-9]{32,}$/i.test(s);return codeLike?'<code class="human-code">'+esc(s)+'</code>':'<span>'+esc(s)+'</span>'}
function humanRender(v,key="",depth=0){if(depth>4)return'<span class="human-muted">Nested detail omitted</span>';if(Array.isArray(v)){if(!v.length)return'<span class="human-muted">None</span>';if(v.every(x=>x===null||["string","number","boolean"].includes(typeof x)))return'<div class="human-chips">'+v.map(x=>'<span class="human-chip">'+humanScalar(key,x)+'</span>').join("")+'</div>';return'<div class="human-list">'+v.map((x,i)=>'<article class="human-card"><div class="human-card-title">'+esc(humanLabel(key||("Item "+(i+1))))+'</div>'+humanRender(x,key,depth+1)+'</article>').join("")+'</div>'}if(v&&typeof v==="object"){const e=Object.entries(v);if(!e.length)return'<span class="human-muted">No data</span>';return'<div class="human-grid">'+e.map(([k,val])=>'<div class="human-row"><div class="human-label">'+esc(humanLabel(k))+'</div><div class="human-value">'+humanRender(val,k,depth+1)+'</div></div>').join("")+'</div>'}return humanScalar(key,v)}
function showHuman(id,value){$(id).innerHTML=humanRender(value)}
function showMessage(id,message,t=""){$(id).innerHTML='<div class="human-message '+t+'">'+esc(message)+'</div>'}

function openView(name){$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+name));$$("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===name));$("view-title").textContent=TITLES[name]||name;window.scrollTo(0,0);if(name==="repo")loadRepo();if(name==="workspace")loadWorkspace();if(name==="visualization")loadArchitecture();if(name==="runtime")loadRuntime();if(name==="controls")loadAssurance();if(name==="logs")loadLogs();if(name==="agents")loadAgents();if(name==="settings")loadSettings()}
$$("[data-view]").forEach(b=>b.onclick=()=>openView(b.dataset.view));$$("[data-open]").forEach(b=>b.onclick=()=>openView(b.dataset.open));
setInterval(()=>{$("clock").textContent=new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})},1000);
const search=$("global-search");search.addEventListener("input",()=>{const q=search.value.trim().toLowerCase();const active=document.querySelector(".view.active");active.querySelectorAll(".panel,.health-card,.human-row,.control-detail,.audit-event,.registry-row").forEach(n=>n.classList.toggle("search-hidden",!!q&&!n.textContent.toLowerCase().includes(q)))});document.addEventListener("keydown",e=>{if(e.key==="/"&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||"")){e.preventDefault();search.focus()}});

function controlRow(c){return'<div class="control-row '+statusClass(c.status)+'"><b>'+esc(c.status)+'</b><span>'+esc(c.title||c.id||c.control_id)+'</span></div>'}
function postureRow(c){return'<div class="posture-item"><i class="'+statusClass(c.status)+'"></i><div><b>'+esc(c.title||humanLabel(c.id))+'</b><small>'+esc(c.detail||c.id||"")+'</small></div><span>'+esc(c.status)+'</span></div>'}
function renderMainLogs(events){$("main-log").innerHTML=events.length?events.slice(-10).reverse().map(x=>'<tr><td>'+esc((x.timestamp||"").slice(11,19)||"—")+'</td><td>'+decisionBadge(x.decision||x.record_type)+'</td><td>'+esc(x.actor||"runtime")+'</td><td>'+esc(x.operation||"—")+'</td></tr>').join(""):'<tr><td colspan="4">No audit records yet.</td></tr>'}
function renderDependencies(d){const rows=(d.items||[]).map(x=>'<div class="dep-row '+(x.installed?"pass":"")+'"><i></i><div><b>'+esc(x.label)+'</b><small>'+esc(x.command)+(x.id==="clamav"?" · signatures "+(x.database_ready?"ready":"missing"):"")+'</small></div><span>'+(x.installed?"READY":"MISSING")+'</span></div>').join("");$("dependency-grid").innerHTML=rows||'<div class="human-empty">No dependency information.</div>'}
function renderMainVM(v){const missing=Object.entries(v.tools||{}).filter(([,x])=>!x).length;const cells=[["KVM",v.kvm?.status||"UNKNOWN"],["Guest assets",v.assets_verified?"VERIFIED":"UNSET"],["QEMU tools",missing?"MISSING "+missing:"READY"],["Mode",v.architecture?.mode||"—"]];$("main-vm").innerHTML=cells.map(([k,val])=>'<div class="status-cell '+tone(val)+'"><small>'+esc(k)+'</small><b>'+esc(val)+'</b></div>').join("")}

async function refreshMain(){try{const [s,events,adv,files]=await Promise.all([api("/api/system"),api("/api/audit/events?limit=30"),api("/api/adversary"),api("/api/files?path=.")]);lastSystem=s;const env=s.environment?.codespaces?"CODESPACES":"LOCAL HOST";$("env-pill").textContent=env;$("boundary-env").textContent=env+" · "+(s.repo.branch||"repo");const protectedState=s.assurance.deployment_complete===true;$("protection").textContent=protectedState?"DEPLOYMENT CONTROLS PASS":"PARTIAL / DEVELOPMENT";$("protection").className="protection-pill "+(protectedState?"pass":"warn");$("boundary-state").textContent=protectedState?"PROTECTED":"PARTIAL BOUNDARY";$("boundary-dot").className="boundary-dot "+(protectedState?"pass":"");$("repo-pill").textContent=(s.repo.branch||"branch")+" @ "+(s.repo.commit||"—")+(s.repo.dirty?" · changed":" · clean");$("hero-mode").textContent=s.runtime.policy_bundle?"signed policy active":"development policy mode";
setHealth("card-engine","ONLINE","BULL runtime and UI adapter responding");setHealth("card-policy",s.runtime.policy_bundle?"SIGNED":"DEV",s.runtime.policy_bundle?"Signed deployment ceiling loaded":"No signed production policy loaded");const kvm=s.vm?.kvm?.status||"BLOCKED";setHealth("card-isolation",kvm==="PASS"?"READY":"BLOCKED",kvm==="PASS"?"KVM device available":"Host does not expose a ready KVM boundary");const auditStatus=s.audit.configured?(s.audit.valid?"VALID":"INVALID"):"UNSET";setHealth("card-audit",auditStatus,(s.audit.records||0)+" ledger records");const ms=s.malware||{};setHealth("card-malware",ms.status||"UNAVAILABLE",ms.ready?"ClamAV + signed database ready":(ms.error||"Scanner not ready"));setHealth("card-sentinel",String(s.sentinel.verdict||"unknown").toUpperCase(),"Score "+Number(s.sentinel.score||0).toFixed(3));
const deps=s.dependencies||{};$("dependency-banner").classList.toggle("hidden",!!deps.ready);$("dependency-text").textContent=deps.ready?"All host tools ready.":"Missing: "+((deps.missing||[]).join(", ")||(!deps.clamav_database_ready?"ClamAV signatures":"host readiness"))+". BULL can install the fixed host tool set.";renderDependencies(deps);
const controls=s.assurance.controls||[];$("main-controls").innerHTML=controls.slice(0,8).map(controlRow).join("");$("posture-list").innerHTML=controls.filter(x=>x.phase==="deployment").slice(0,8).map(postureRow).join("")||'<div class="human-empty">No control evidence.</div>';$("m-observed").textContent=adv.summary?.total_attackers||0;$("m-swarms").textContent=Object.keys(adv.summary?.swarms||{}).length;$("m-quarantine").textContent=adv.summary?.quarantined||0;$("m-audit").textContent=s.audit.records||0;$("recent-alerts").innerHTML=events.filter(x=>["DENY","ESCALATE"].includes(String(x.decision).toUpperCase())).slice(-5).reverse().map(x=>'<div class="alert">'+esc(x.decision)+" · "+esc(x.operation||"event")+"<br>"+esc(x.resource||"")+"</div>").join("")||'<div class="human-empty">No deny or escalate events in the current audit window.</div>';$("repo-summary").innerHTML="<b>"+esc(s.repo.remote||"No remote")+"</b><br>Branch "+esc(s.repo.branch)+" · commit "+esc(s.repo.commit)+"<br>Working tree "+(s.repo.dirty?"has changes":"is clean");$("mini-files").innerHTML=(files.items||[]).slice(0,9).map(x=>'<div>'+(x.dir?"▣ ":"· ")+esc(x.path)+'</div>').join("");renderMainLogs(events);renderMainVM(s.vm||{});$("malware-readiness").textContent=ms.ready?"READY":(ms.status||"UNAVAILABLE")}catch(e){$("protection").textContent="DASHBOARD ERROR";$("protection").className="protection-pill fail";toast(e.message,"error")}}
setInterval(refreshMain,5000);

async function installHost(){try{const j=await post("/api/host/install");selectedJob=j.id;toast("Host dependency install started","success");openView("runtime");await refreshJobs()}catch(e){toast(e.message,"error")}}
$("host-install").onclick=installHost;$("settings-install").onclick=installHost;

async function browse(path="."){const x=await api("/api/files?path="+encodeURIComponent(path));currentRepoPath=x.path;$("repo-path").textContent=x.path;const el=$("repo-browser");el.innerHTML="";if(x.path!=="."){const up=document.createElement("button");up.className="dir";up.textContent="↰ ..";up.onclick=()=>browse(x.path.split("/").slice(0,-1).join("/")||".");el.appendChild(up)}x.items.forEach(it=>{const b=document.createElement("button");b.className=it.dir?"dir":"";b.textContent=(it.dir?"▣ ":"· ")+it.name;b.onclick=()=>it.dir?browse(it.path):previewFile(it.path);el.appendChild(b)})}
async function previewFile(path){try{const x=await api("/api/file?path="+encodeURIComponent(path));$("file-preview").textContent=x.content}catch(e){$("file-preview").textContent=e.message}}
async function loadRepo(){const s=await api("/api/repo");showHuman("repo-json",s);$("changed-files").innerHTML=s.status.length?s.status.map(x=>'<div>'+esc(x)+'</div>').join(""):"<div>Working tree clean.</div>";await browse(currentRepoPath)}
$("repo-refresh").onclick=loadRepo;

async function loadWorkspace(){const x=await api("/api/files?path=.");$("workspace-tree").innerHTML=x.items.map(it=>'<button data-p="'+esc(it.path)+'" class="'+(it.dir?"dir":"")+'">'+(it.dir?"▣ ":"· ")+esc(it.path)+'</button>').join("");$$('#workspace-tree button').forEach(b=>b.onclick=()=>{$("malware-path").value=b.dataset.p})}
$("malware-scan").onclick=async()=>{try{showMessage("malware-result","Scanning with BULL's bounded ClamAV path…");showHuman("malware-result",await post("/api/malware/scan",{path:$("malware-path").value}))}catch(e){showMessage("malware-result",e.message,"error")}};

let arch=null;
async function loadArchitecture(){arch=await api("/api/architecture");$("architecture-graph").innerHTML=arch.nodes.map(n=>'<div class="arch-node"><b>'+esc(n.label)+'</b><span>'+esc(n.group)+'</span></div>').join("");for(const id of ["p-capability","p-granted"]){$(id).innerHTML=arch.capabilities.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("")}$("p-provenance").innerHTML=arch.provenance.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join("");$("p-capability").value="fs.read.project";$("p-provenance").value="human";[...$("p-granted").options].forEach(o=>o.selected=o.value==="fs.read.project")}
$("policy-evaluate").onclick=async()=>{const granted=[...$("p-granted").selectedOptions].map(o=>o.value);const payload={actor:$("p-actor").value,task:"BULL UI policy test",operation:$("p-operation").value,resource:$("p-resource").value,capability:$("p-capability").value,granted_capabilities:granted,provenance:[$("p-provenance").value]};try{showHuman("policy-result",await post("/api/policy/evaluate",payload))}catch(e){showMessage("policy-result",e.message,"error")}};
$("trace-run").onclick=async()=>{const events=[{transition:"Evaluate",data:{decision:$("trace-decision").value}}];if($("trace-scan").checked)events.push({transition:"ScanClean",data:{}});if($("trace-execute").checked)events.push({transition:"Execute",data:{sandboxed:$("trace-sandbox").checked,seccomp:$("trace-seccomp").checked}});try{showHuman("trace-result",await post("/api/trace/simulate",{events}))}catch(e){showMessage("trace-result",e.message,"error")}};

async function loadRuntime(){try{const v=await api("/api/vm");$("vm-kvm").textContent=v.kvm?.status||"UNKNOWN";$("vm-assets").textContent=v.assets_verified?"VERIFIED":v.asset_manifest?"INVALID":"UNSET";const missing=Object.entries(v.tools||{}).filter(([,x])=>!x).map(([k])=>k);$("vm-tools").textContent=missing.length?"MISSING "+missing.length:"READY";$("vm-mode").textContent=v.architecture?.mode||"—";showHuman("vm-state",v)}catch(e){showMessage("vm-state",e.message,"error")}await refreshJobs()}
async function refreshJobs(){try{const jobs=await api("/api/jobs");$("job-list").innerHTML=jobs.length?jobs.map(j=>'<button class="job '+statusClass(j.status)+'" data-job="'+esc(j.id)+'"><b>'+esc(j.status)+'</b><span>'+esc(j.command_label)+'</span><small>'+esc(new Date((j.started||0)*1000).toLocaleString())+'</small></button>').join(""):'<div class="human-empty">No runtime jobs launched in this session.</div>';$$("[data-job]").forEach(b=>b.onclick=()=>selectJob(b.dataset.job));if(selectedJob)await selectJob(selectedJob,false)}catch(e){$("job-list").innerHTML='<div class="human-empty">'+esc(e.message)+'</div>'}}
async function selectJob(id,remember=true){if(remember)selectedJob=id;try{const [j,l]=await Promise.all([api("/api/job?id="+encodeURIComponent(id)),api("/api/job/log?id="+encodeURIComponent(id))]);$("job-log").innerHTML='<div class="job-meta">'+humanRender(j)+'</div><div class="console-log"><div class="console-log-title">CAPTURED RUNTIME LOG</div><pre>'+esc(l.log||"No log output yet.")+'</pre></div>'}catch(e){showMessage("job-log",e.message,"error")}}
$("vm-refresh").onclick=loadRuntime;$("jobs-refresh").onclick=refreshJobs;
$("vm-install-assets").onclick=async()=>{try{const j=await post("/api/vm/install-assets");selectedJob=j.id;toast("Verified guest download started","success");await refreshJobs()}catch(e){toast(e.message,"error")}};
$("vm-plan").onclick=async()=>{try{showHuman("job-log",await api("/api/microvm/plan"))}catch(e){showMessage("job-log",e.message,"error")}};
$("vm-run").onclick=async()=>{try{const j=await post("/api/vm/run",{case:$("vm-case").value});selectedJob=j.id;toast("KVM job started","success");await refreshJobs()}catch(e){toast(e.message,"error")}};
$("deployment-run").onclick=async()=>{try{const j=await post("/api/deployment/run");selectedJob=j.id;toast("Deployment check started","success");await refreshJobs()}catch(e){toast(e.message,"error")}};
setInterval(()=>{if($("view-runtime").classList.contains("active"))refreshJobs()},2500);

async function loadAssurance(){const a=await api("/api/assurance");$("a-source").textContent=String(a.source_complete).toUpperCase();$("a-deploy").textContent=String(a.deployment_complete).toUpperCase();$("a-release").textContent=a.release_complete===null?"NOT RUN":String(a.release_complete).toUpperCase();$("a-profile").textContent=a.profile||"—";$("assurance-controls").innerHTML=(a.controls||[]).map(c=>'<div class="control-detail"><div class="status '+statusClass(c.status)+'">'+esc(c.status)+'</div><div><b>'+esc(c.title||humanLabel(c.id))+'</b><small>'+esc(c.id)+'</small></div><div>'+esc(c.detail||"No additional deployment detail.")+'</div><div>'+esc(humanLabel(c.phase))+'</div></div>').join("")}
$("assurance-refresh").onclick=loadAssurance;

async function loadLogs(){const [a,e]=await Promise.all([api("/api/audit"),api("/api/audit/events?limit=150")]);$("l-config").textContent=a.configured?"YES":"NO";$("l-valid").textContent=a.valid===true?"VALID":a.valid===false?"INVALID":"—";$("l-records").textContent=a.records||0;$("l-head").textContent=(a.head_hash||"—").slice(0,14);$("audit-events").innerHTML=e.length?e.reverse().map(x=>'<div class="audit-event"><span>'+esc(x.timestamp||"")+'</span><span>'+decisionBadge(x.decision||x.record_type)+'</span><span>'+esc(x.actor||"runtime")+'</span><span>'+esc((x.operation||"")+" "+(x.resource||""))+'</span><span class="hash">'+esc(x.record_hash||"")+'</span></div>').join(""):'<div class="human-empty">No audit events available.</div>'}
$("log-refresh").onclick=loadLogs;

function registryHtml(a){const rows=a.records||[];return rows.length?rows.map(r=>'<div class="registry-row"><span>'+esc(r.attacker_id)+'</span><span>'+esc(r.label)+'</span><span>'+esc(r.swarm_id||"—")+'</span><span>'+esc(r.model_family)+'</span><button data-q="'+esc(r.attacker_id)+'">'+(r.quarantined?"QUARANTINED":"CLASSIFY QUARANTINE")+'</button></div>').join(""):'<div class="human-empty">No observed records yet.</div>'}
async function refreshRegistry(){const a=await api("/api/adversary");$("adversary-registry").innerHTML=registryHtml(a);$$("[data-q]").forEach(b=>b.onclick=async()=>{if(b.textContent==="QUARANTINED")return;try{await post("/api/adversary/quarantine",{attacker_id:b.dataset.q});await refreshRegistry();await refreshMain()}catch(e){toast(e.message,"error")}})}
async function loadAgents(){const [s,a]=await Promise.all([api("/api/sentinel"),api("/api/adversary")]);$("sentinel-score").textContent=Number(s.score||0).toFixed(3);$("sentinel-verdict").textContent=String(s.verdict||"unknown").toUpperCase();showHuman("sentinel-signals",s.signals||{});$("adversary-registry").innerHTML=registryHtml(a);await refreshRegistry()}
$("agent-refresh").onclick=refreshRegistry;
$("agent-scan").onclick=async()=>{const payload={};if($("agent-url").value.trim())payload.url=$("agent-url").value.trim();else payload.text=$("agent-text").value;try{const r=await post("/api/agent-scan",payload);showHuman("agent-scan-result",r);lastScan=r.counts||lastScan;await refreshRegistry();await refreshMain()}catch(e){showMessage("agent-scan-result",e.message,"error")}};

async function loadSettings(){const [s,b,d]=await Promise.all([api("/api/system"),api("/api/brand"),api("/api/host/dependencies")]);showHuman("runtime-json",s.runtime);renderDependencies(d);$("brand-revision").textContent=b.revision||"";$("brand-meta").innerHTML="<b>Approved source:</b> "+esc(b.source?.file||"")+" · "+esc(b.source?.note||"")+"<br><b>SHA-256:</b> "+esc(b.source?.sha256||"");$("brand-assets").innerHTML=Object.keys(b.files||{}).map(name=>'<div class="brand-asset '+(name.includes("primary.svg")?"light":"")+'"><img src="/brand/'+encodeURIComponent(name)+'" alt="'+esc(name)+'"><span>'+esc(name)+'</span></div>').join("")}

refreshMain();loadArchitecture();
