# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pagination.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pagination.proto\x12 openshell.internal.pagination.v1\"\xe1\x02\n\tPageToken\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x1b\n\x13request_fingerprint\x18\x03 \x01(\x0c\x12@\n\x06object\x18\x04 \x01(\x0b\x32..openshell.internal.pagination.v1.ObjectCursorH\x00\x12@\n\x06policy\x18\x05 \x01(\x0b\x32..openshell.internal.pagination.v1.PolicyCursorH\x00\x12\x42\n\x07profile\x18\x06 \x01(\x0b\x32/.openshell.internal.pagination.v1.ProfileCursorH\x00\x12\x44\n\x08provider\x18\x07 \x01(\x0b\x32\x30.openshell.internal.pagination.v1.ProviderCursorH\x00\x42\x08\n\x06\x63ursor\"R\n\x0cObjectCursor\x12\x15\n\rcreated_at_ms\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tworkspace\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1f\n\x0cPolicyCursor\x12\x0f\n\x07version\x18\x01 \x01(\x03\"\x1c\n\rProfileCursor\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0eProviderCursor\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAGETOKEN']._serialized_start=55
  _globals['_PAGETOKEN']._serialized_end=408
  _globals['_OBJECTCURSOR']._serialized_start=410
  _globals['_OBJECTCURSOR']._serialized_end=492
  _globals['_POLICYCURSOR']._serialized_start=494
  _globals['_POLICYCURSOR']._serialized_end=525
  _globals['_PROFILECURSOR']._serialized_start=527
  _globals['_PROFILECURSOR']._serialized_end=555
  _globals['_PROVIDERCURSOR']._serialized_start=557
  _globals['_PROVIDERCURSOR']._serialized_end=587
# @@protoc_insertion_point(module_scope)
